export const DEFAULT = "DEFAULT";
export const UPDATE_NUM = "UPDATE_NUM";
export const INCREASE_BREAK_LENGTH_INDEX = "INCREASE_BREAK_LENGTH_INDEX";
export const INCREASE_BREAK_LENGTH = "INCREASE_BREAK_LENGTH";